#!/bin/bash

php -S localhost:8000 &
pid=$!  # pid of the php server
trap "kill $pid 2> /dev/null" EXIT  # If this script is killed, kill the php server
gnome-open http://localhost:8000/generate.php
read -p "Press [Enter] key to kill php server"
